services:
  - type: web
    name: django-library
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn lms.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: PYTHON_VERSION
    plan: free
