services:
  - type: web
    name: django-library
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn manage:app"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "<your-secret-key>"
    plan: free
